# Generated by Django 4.0.2 on 2022-03-04 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 12, 52, 48, 50123), verbose_name='date published'),
        ),
    ]
